# Generated by Django 3.1.5 on 2021-04-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=80, unique=True)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('blurb', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=80, unique=True)),
                ('p_keys', models.CharField(max_length=160, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('img', models.ImageField(upload_to='')),
                ('s_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shop')),
            ],
        ),
    ]
