# Generated by Django 3.1.5 on 2021-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_shop_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='distance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
