# Generated by Django 3.1.5 on 2021-04-23 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210422_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='blurb',
        ),
        migrations.AddField(
            model_name='product',
            name='p_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='s_link',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
